### ISSUE TITLE
[Joss review] Test tolerance and sample sizes

### ISSUE THREAD

**Issue by CamDavidsonPilon** [derrynknife/SurPyval#17]
I'd like to see tighter tolerances in the tests, and tests with smaller samples sizes. Currently the [TOL](https://github.com/derrynknife/SurPyval/commit/d1105f13342d0b4368a1b7197ac5d5d0788933b6) is set to 0.2 - this is quite a large margin, practically useless in some cases. The minimum sample size is 5000 - that's medium-sized data, but how well do the algorithms work for small size data (sub 100, for example). 

https://github.com/openjournals/joss-reviews/issues/3484

**Comment by derrynknife** [comment]
Fair, I changed it to 20% because the git workflows seemed to not converge as well as my local machine. I've changed it back to much finer tolerances and split the convergence into two tests. A large scale convergence and a small sample convergence. 


commit d4df11ff7c13aa372ee843d6585751282706de98
