### ISSUE TITLE
Gumbel distribution

### ISSUE THREAD

**Issue by lisandrojim** [derrynknife/SurPyval#31]
I was giving a look at the survival function of the [Gumbel distribution](https://github.com/derrynknife/SurPyval/blob/master/surpyval/parametric/gumbel.py), and I found that it is defined as:

`S(x) = np.exp(-np.exp((x - mu)/sigma))`

Shouldn't it be:

`S(x) = 1 - np.exp(-np.exp(-(x - mu)/sigma))`

I changed it manually in the code, and when I fitted the function the problem was not solved (i.e., the fitting is still done with the first equation shown above). Any suggestions on what to do?

**Comment by derrynknife** [comment]
You might have to change the ff function as well

Thanks for picking that up!

**Comment by lisandrojim** [comment]
Updating the `ff` function solved the problem. However, the values of the hazard function `h(x)` and cumulative hazard `H(x)` need to be adjusted as well as follows:

**Hazard function:**
`
h(x) =  (1/sigma) * np.exp(- (x - mu) / sigma)
`
**Cumulative hazard function:**
`H(x) = np.exp(-(x - mu)/sigma)`

The quantile function (`qf`) for the Gumbel Distribution still needs to be adjusted so that the `random` function works correctly. I hope you can update the code with these changes.

**Comment by derrynknife** [comment]
Could you do a pull request?

**Comment by lisandrojim** [comment]
Hello Derryn,

I just made the pull request. I never did it before, so I hope it worked just fine. Let me know otherwise.

Cheers, Lisandro

**Comment by derrynknife** [comment]
G'Day Lisandro.

I've just had a look at this, and in a way, we are both correct.

The current implementation of the Gumbel distribution in surpyval, is actually the "Smallest Extreme Value" version of the Gumbel distribution. See [here](https://reliawiki.org/index.php/The_Gumbel/SEV_Distribution) for information regarding it. The smallest extreme value distribution is more useful in survival analysis as it captures a weakest link type of failure.

The implementation of the Gumbel you are suggesting is, correctly, a "Gumbel" distribution, although it is the "Largest Extreme Value" version of it. If you want, and instead of changing the current implementation, we can add a new distribution that captures this. Perhaps we can call it, "LEV" or Gumbel2 or something?

I'll close this issue, but please feel free to raise another with your preferred direction.

**Comment by lisandrojim** [comment]
Hello Derryn,

Thanks for the clarification. 

There are two possibilities I see:

1. Rename the current gumble.py script to e.g., gumbel_lev.py, and create a new script called gumble.py with the changes I suggested. Note: Please also ensure that all the remaining functions are working accordingly. 

or.

2. Add an additional input variable to the current gumbel.py function, where the user can choose between the distribution's extreme maximum or minimum value.

I think the easiest is option 1. Let me know if I can help you with this.

Regards,
Lisandro
